# --------------------------------------------------
# Dependencies
# --------------------------------------------------
FROM node:22-alpine AS deps

WORKDIR /app

RUN apk add --no-cache git

COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./

RUN npm ci

# --------------------------------------------------
# Worker
# --------------------------------------------------
FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache \
    git \
    docker-cli

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production

CMD ["npm","run","worker"]