apiVersion: v1
kind: Service
metadata:
  name: marketsphere-redis
  labels:
    app: marketsphere-redis
spec:
  type: ClusterIP
  selector:
    app: marketsphere-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
