apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketsphere-worker
  namespace: marketsphere

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: marketsphere-worker
  namespace: marketsphere
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: marketsphere-worker
  namespace: marketsphere
subjects:
  - kind: ServiceAccount
    name: marketsphere-worker
    namespace: marketsphere
roleRef:
  kind: Role
  name: marketsphere-worker
  apiGroup: rbac.authorization.k8s.io
